### ISSUE TITLE
Can not be parsed correctly.

### ISSUE THREAD

**Issue by flyaway1217** [quentin-chen/hexo-reference#1]
I am using hexo-renderer-markdown-it plugin and Next theme.
When I add this plugin, I got this:
![wx20161230-102639](https://cloud.githubusercontent.com/assets/1570846/21569497/8ee14190-ce7a-11e6-9460-874df02abdde.png)
![wx20161230-102739](https://cloud.githubusercontent.com/assets/1570846/21569502/9d3b7058-ce7a-11e6-887e-f4bf7d5d9be5.png)

**Comment by quentin-chen** [comment]
`hexo-renderer-markdown-it` has conflict with `hexo-reference`, cuz it defines another way to render footnotes which differs from official `hexo-renderer-marked`. So you should choose one of them to render footnotes.

Thanks
