### ISSUE TITLE
how can I use parenthesis in notes?

### ISSUE THREAD

**Issue by oupala** [quentin-chen/hexo-reference#3]
When I use notes, I sometime want to use parenthesis in notes.

When I use them, the closing parenthesis is closing the note whereas it should only close the last opening parenthesis.

Is there a way to use parenthesis in notes?

**Comment by quentin-chen** [comment]
Multi-Markdown supports two style of footnotes just like links: *inline* and *reference*.

So use *reference* instead of *inline* should correctly render parenthesis in footnote.

**Comment by oupala** [comment]
Great answer. You're right.

Thanks for all!
