### ISSUE TITLE
想修改配色应该怎么做？

### ISSUE THREAD

**Issue by moonaileen** [quentin-chen/hexo-reference#8]
您好，用了一下这个感觉很好，就是配色跟主题不是很搭，如果想修改配色应该修改hint.min.css中的哪个部分呢？
比较小白，可能问了个傻问题，还请见谅><

**Comment by tsanie** [comment]
+1

我也没有找到配置的地方，目前想要修改的话只有修改 `.hint--error` 的那几个 `background-color` 项

**Comment by quentin-chen** [comment]
修改此行：

https://github.com/quentin-chen/hexo-reference/blob/a86714fe2c2d19b7695dbe9ac571a1e12ff3b81c/src/footnotes.js#L58

的 `class` 属性，可选：

hint--error, hint--info, hint--warning, hint--success
